//LOCALHOST Employee Collection

### Get Employee list
GET http://localhost:3000/employee HTTP/1.1
### Get Employee by Id
GET http://localhost:3000/employee/6452e0c8e12 HTTP/1.1

### Create Employee
POST http://localhost:3000/employee HTTP/1.1
Content-Type: application/json

{
    "firstName": "Michael",
    "lastName": "Smith",
    "gender": "Male",
    "personalEmail": "michaelsmith@gmail.com",
    "jobTitle": "Produce Department Manager",
    "workEmail": "michaelsmith@grocerystore.com"
}

### Update a Employee
PUT http://localhost:3000/employee/645333785 HTTP/1.1
content-type: application/json

{
    "firstName": "Michael",
    "lastName": "Smith",
    "gender": "Male",
    "personalEmail": "michaelsmith@gmail.com",
    "jobTitle": "Store Manager",
    "workEmail": "michaelsmith@grocerystore.com"
}

### Delete Employee
DELETE http://localhost:3000/employee/645333785 HTTP/1.1



=======
//LOCALHOST Products Collection
### Get produce list
GET http://localhost:3000/produce HTTP/1.1
Content-Type: application/json

### Get Character by Id
GET http://localhost:3000/produce/645f067e4a28bac2b7783970 HTTP/1.1
Content-Type: application/json

### Create Character
POST http://localhost:3000/produce HTTP/1.1
Content-Type: application/json

   {
    "department": "produce",
    "type": "vegetable",
    "color": "green",
    "quality": "superior",
    "peakSeason": "year around", 
	"amountInStock": 5,
    "unit":"head",
    "productName": "Lettuce",
	}

### Update a Character
PUT http://localhost:3000/produce/645f07b64a28bac2b7783972 HTTP/1.1
content-type: application/json

{
	"productName": "Beets",
    "department": "produce",
    "type": "vegetable",
    "color": "purple",
    "quality": "superior",
    "peakSeason": "October", 
	"unit":"bunch",
	"amountInStock": 5,
	"pricePerUnit": 2.00
	}

### Delete Product
DELETE http://localhost:3000/produce/645f07b64a28bac2b7783972 HTTP/1.1

### create seasonal item
POST http://localhost:3000/seasonal HTTP/1.1
content-type: application/application/json

{
    "department": "seasonal",
    "type": "pool supply",
    "color": "blue",
    "size": "medium",
    "season": "Summer",
    "amountInStock": "32",
    "unit": "single",
    "productName": "Blue Pool Noodle",
    }

//LOCALHOST Planets Collection
### Get Planet list
GET http://localhost:3000/planets HTTP/1.1
### Get Planet by Id
GET http://localhost:3000/planets/6452e25ee12b6022b2bdcf59 HTTP/1.1

### Create Planet
POST http://localhost:3000/planets HTTP/1.1
Content-Type: application/json

{
    "planetName":"Lothal",
    "region":"Outer Rim",
    "sector":"Lothal Sector",
    "suns":"1",
    "moons":"2",
    "terrain":"Prairies"
}

### Update a Planet
PUT http://localhost:3000/planets/645333c05cb09e305b571c5d HTTP/1.1
content-type: application/json

{
    "planetName":"Lothal",
    "region":"Outer Rim",
    "sector":"Lothal Sector",
    "suns":"1",
    "moons":"2",
    "terrain":"Mountains"
}

### Delete Planet
DELETE http://localhost:3000/planets/6455bddf8a1a279f08700b20 HTTP/1.1

//PRODUCTION Deploy
### Get Produce list
GET https://ryanalvordcit341.onrender.com/produce HTTP/1.1

### Get Product by Id
GET https://ryanalvordcit341.onrender.com/produce/645f067e4a28bac2b7783970 HTTP/1.1

### Create Produce
POST https://cte341-final-project.onrender.com/produce HTTP/1.1
Content-Type: application/json

{
	"productName": "chives",
    "department": "produce",
    "type": "vegetable",
    "color": "green",
    "quality": "superior",
    "peakSeason": "year around", 
	"unit":"bunch",
	"amountInStock": 5,
	"pricePerUnit": 1.50
	}

### Update a Produce
PUT https://cte341-final-project.onrender.com/produce/645f067e4a28bac2b7783970 HTTP/1.1
content-type: application/json

{
    "department": "produce",
    "type": "vegetable",
    "color": "green",
    "quality": "superior",
    "peakSeason": "year around", 
	"amountInStock": 10,
    "unit":"bunch",
    "productName": "chives",
	}

### Delete Product
DELETE https://cte341-final-project.onrender.com/produce/645f08be4a28bac2b7783976 HTTP/1.1
### create seasonal item 

POST https://cte341-final-project.onrender.com/seasonal HTTP/1.1
content-type: application/application/json

{
    "department": "seasonal",
    "type": "pool supply",
    "color": "blue",
    "size": "medium",
    "season": "Summer",
    "amountInStock": "32",
    "unit": "single",
    "productName": "Blue Pool Noodle",
    }

//LOCALHOST Planets Collection
### Get Planet list
GET https://ryanalvordcit341.onrender.com/planets HTTP/1.1
### Get Planet by Id
GET https://ryanalvordcit341.onrender.com/planets/6452e25ee12b6022b2bdcf59 HTTP/1.1

### Create Planet
POST https://ryanalvordcit341.onrender.com/planets HTTP/1.1
Content-Type: application/json

{
    "planetName":"Lothal",
    "region":"Outer Rim",
    "sector":"Lothal Sector",
    "suns":"1",
    "moons":"2",
    "terrain":"Prairies"
}

### Update a Planet
PUT https://ryanalvordcit341.onrender.com/planets/645333c05cb09e305b571c5d HTTP/1.1
content-type: application/json

{
    "planetName":"Lothal",
    "region":"Outer Rim",
    "sector":"Lothal Sector",
    "suns":"1",
    "moons":"2",
    "terrain":"Mountains"
}

### Delete Planet
DELETE https://ryanalvordcit341.onrender.com/planets/6455c05067c4ce408fe6e571 HTTP/1.1


{
    "name": "sample",
    "time": "Wed, 21 Oct 2015 18:27:50 GMT"
}